# Generated by Django 3.2.2 on 2021-05-19 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('accounts', '0002_hirerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bio', models.TextField()),
                ('remote', models.BooleanField(default=False)),
                ('fixed_term', models.BooleanField(default=False)),
                ('min_pay', models.IntegerField()),
                ('image', models.URLField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.IntegerField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
                ('skill', models.ManyToManyField(related_name='talent_profile', to='categories.Subcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
