# Generated by Django 3.2.2 on 2021-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_talentprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talentprofile',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
