# Generated by Django 3.2.2 on 2021-05-22 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_profile_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talentprofile',
            old_name='skill',
            new_name='skills',
        ),
    ]
