# Generated by Django 3.2.2 on 2021-05-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_skill_talentprofile_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerprofile',
            name='postal_code',
            field=models.IntegerField(null=True),
        ),
    ]
