# Generated by Django 3.2.2 on 2021-05-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_hirerprofile_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirerprofile',
            name='company',
            field=models.CharField(max_length=255),
        ),
    ]
