# Generated by Django 3.2.2 on 2021-05-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_hirerprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerprofile',
            name='image',
            field=models.URLField(default='https://i.imgur.com/vWQLCe6.png'),
        ),
    ]
