# Generated by Django 3.2.2 on 2021-06-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_hirerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirerprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
