# Generated by Django 3.2.2 on 2021-05-20 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0006_alter_gig_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentFav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied', models.ManyToManyField(related_name='talent_applied', to='gigs.Gig')),
                ('invited', models.ManyToManyField(related_name='talent_invited', to='gigs.Gig')),
                ('saved', models.ManyToManyField(related_name='talent_saved', to='gigs.Gig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='talent_fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
