# Generated by Django 3.2.2 on 2021-05-22 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_talentprofile_postal_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HirerFav',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('saved', models.ManyToManyField(related_name='talent_saved', to='accounts.TalentProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hirer_fav', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
