# Generated by Django 3.2.2 on 2021-05-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_remote', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('hour_rate', models.IntegerField(null=True)),
                ('fixed_amount', models.IntegerField(null=True)),
                ('duration', models.IntegerField()),
                ('address', models.CharField(max_length=255, null=True)),
                ('postal_code', models.IntegerField(blank=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('close', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('is_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_owner', to=settings.AUTH_USER_MODEL)),
                ('subcategories', models.ManyToManyField(related_name='gigs', to='categories.Subcategory')),
                ('winner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
