# Generated by Django 3.2.2 on 2021-05-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_auto_20210519_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='duration_unit',
            field=models.CharField(default='day', max_length=100),
            preserve_default=False,
        ),
    ]
