# Generated by Django 3.2.2 on 2021-05-20 10:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0004_remove_gig_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='expired_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
