# Generated by Django 3.2.2 on 2021-05-20 11:09

from django.db import migrations, models
import gigs.models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0005_gig_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='expired_at',
            field=models.DateTimeField(default=gigs.models.add_one_month),
        ),
    ]
