# Generated by Django 3.2.2 on 2021-05-21 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0007_rename_close_gig_is_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='completed',
            new_name='is_completed',
        ),
    ]
