# Generated by Django 3.2.2 on 2021-05-28 01:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0009_auto_20210522_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='flag',
            field=models.ManyToManyField(related_name='gigs_flag', to=settings.AUTH_USER_MODEL),
        ),
    ]
