# Generated by Django 3.2.2 on 2021-06-02 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0010_gig_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='gigs_flag', to=settings.AUTH_USER_MODEL),
        ),
    ]
