# Generated by Django 3.2.2 on 2021-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='new message', max_length=255),
            preserve_default=False,
        ),
    ]
